### ISSUE TITLE
No data for Macedonia.

### ISSUE THREAD

**Issue by ghost** [markuslerner/travelscope#12]
Hello, first of all, thank you for this amazing project! 

But I can't figure out why the Macedonian data is not showing?  And for some countries the data is wrong

Kind regards!

**Comment by markuslerner** [comment]
Thank you for pointing this out. The URL of the visa requirements Wikipedia page for Macedonian citizens had changed. I just fixed this now.

**Comment by ghost** [comment]
Great thanks!

Can you also check why for Northern Cyprus, Swatinii, Sao Tome and Principe, Pakistan and northern Cyprus there is no data?

Thanks in advance!

**Comment by markuslerner** [comment]
Swatinii and Sao Tome and Principe are now fixed (javascript string matching fix).

Pakistan is fixed as well (more lenient check when detecting visa requirements table in php).

Northern Cyprus can't be fixed, because there is no table in the Wikipedia page like for the other countries:
https://en.wikipedia.org/wiki/Visa_requirements_for_Northern_Cypriot_citizens
