### ISSUE TITLE
No data for some countries

### ISSUE THREAD

**Issue by tomasbal** [markuslerner/travelscope#13]
Hello,

Thank you for this great app! I'm just wondering, why there is no data for some of the countries?

There is no data for:
-Northern Cyprus, 
-Macedonia (i see that there was open issue for Macedonia and it says that its have been fixed, but i just compiled it and it's not working), 
-Sao Tome and Principe, 
-eSwatini,
-Northern Cyprus/N. Cyprus

Thanks in advance!

**Comment by markuslerner** [comment]
Macedonia is fixed, but probably didn't show up, because the development visa requirements url used in src/index.html was still the old one.

Swatinii and Sao Tome and Principe are now fixed (javascript string matching fix).

Pakistan is fixed as well (more lenient check when detecting visa requirements table in php).

Northern Cyprus can't be fixed, because there is no table in the Wikipedia page like for the other countries:
https://en.wikipedia.org/wiki/Visa_requirements_for_Northern_Cypriot_citizens
