### ISSUE TITLE
Moroccan's map isn't full

### ISSUE THREAD

**Issue by V0id09** [markuslerner/travelscope#36]
Hello fellow programmers, i salute you for your hard work to deliver us a great responsive site as yours,but i faced a huge problem wich is Morocco's map (my origin) isn't full. It may be due to late update after the declaration of USA that the sahara belongs to Morocco and that's a fact. So please update your global map and show the full Size of Morocco. Thank you for your hard work.

**Comment by markuslerner** [comment]
Thank you, @V0id09 for your compliments and your feedback. Travelscope uses map data from [Natural Earth](https://www.naturalearthdata.com/), including the default disputed area maps and adopts the [Natural Earth Disputed Boundaries Policy](https://www.naturalearthdata.com/about/disputed-boundaries-policy/): »Natural Earth draws boundaries of sovereign states according to de facto (“in fact”) status rather than de jure (“by law”). We show who actually controls the situation on the ground because it turns out laws vary country to country, and countries are only loosely bound by international law in their dealings with each other. While our de facto policy does not please everyone, it is rigorous and self consistent.« Thank you for your understanding.
