### ISSUE TITLE
Taiwan

### ISSUE THREAD

**Issue by trevorpowell** [markuslerner/travelscope#5]
Something is up with the data for Taiwan, maybe due to its international political status. U.S. citizens can travel to Taiwan visa-free for 90 days and vice versa, but that doesn't seem to be displayed correctly.
https://en.wikipedia.org/wiki/Visa_requirements_for_United_States_citizens

**Comment by markuslerner** [comment]
Thank you for pointing this out!

It looks like the structure of the data on Wikipedia has changed and my parser doesn't read the data from all the tables.

I will look into this as soon as I have the time to do so.

Best
Markus

**Comment by markuslerner** [comment]
Thank you for pointing this out.

The underlying problem is that the data for special regions like Taiwan (territories, disputed areas, partially recognized countries and restricted zones) are not entered in tabular form for for all countries yet. So I'm generally not loading these data for all countries in order to be fair and to keep the ranking among the countries comparable.

Besides that, there was a bug in the way the info was displayed for US citizen travelling to Taiwan, now it shows 'data not available' for the time being.
